### ISSUE TITLE
Unable to launch due to missing OpenGL context.

### ISSUE THREAD

**Issue by kamfretoz** [caol64/ps2mc-browser#2]
Hello, I've been trying to setup PS2MC on my Arch Linux and i couldn't get it to run, not sure if i missed something.
Please let me know if you need more information.

Here is the traceback:
```
Traceback (most recent call last):
File "/home/kamfretoz/stuff/pcsx2-appimage/ps2mc-browser/src/wxwindow.py", line 9, in OnInit
frame = WxFrame("PS2 memory card browser")
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/kamfretoz/stuff/pcsx2-appimage/ps2mc-browser/src/wxwindow.py", line 24, in __init__
self.canvas = WxCanvas(self)
				^^^^^^^^^^^^^^
File "/home/kamfretoz/stuff/pcsx2-appimage/ps2mc-browser/src/wxcanvas.py", line 29, in __init__
self.ctx = mgl.create_context()
			^^^^^^^^^^^^^^^^^^^^
File "/home/kamfretoz/stuff/pcsx2-appimage/ps2mc-browser/.venv/lib/python3.11/site-packages/moderngl/__init__.py", line 2174, in create_context
ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
							^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/kamfretoz/stuff/pcsx2-appimage/ps2mc-browser/.venv/lib/python3.11/site-packages/glcontext/__init__.py", line 90, in create
return x11.create_context(**kwargs)
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: (detect) glXGetCurrentContext: cannot detect OpenGL context
OnInit returned false, exiting...
```

System Information:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.9-273-tkg-linux-keronel (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550M AORUS PRO
```

**Comment by caol64** [comment]
hi @kamfretoz 

It seems that wxPython failed to create an OpenGL context, which causes ModerGL to be unable to bind to the context. Try upgrading wxPython to [4.2.1 (phoneix)](https://pypi.org/project/wxPython/4.2.1/) and moderngl to [5.8.2](https://pypi.org/project/moderngl/).

Regards.

**Comment by kamfretoz** [comment]
> hi @kamfretoz
> 
> It seems that wxPython failed to create an OpenGL context, which causes ModerGL to be unable to bind to the context. Try upgrading wxPython to [4.2.1 (phoneix)](https://pypi.org/project/wxPython/4.2.1/) and moderngl to [5.8.2](https://pypi.org/project/moderngl/).
> 
> Regards.

It seems i already have that specific version installed but it still doesn't work.
```
Requirement already satisfied: wxPython==4.2.1 in ./.venv/lib/python3.11/site-packages (4.2.1)
Requirement already satisfied: moderngl==5.8.2 in ./.venv/lib/python3.11/site-packages (5.8.2)
```
